version: '3.8'
services:
  becalm-frontend:
    build: ./becalm-frontend
    ports:
      - "8033:8033"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.becalm-frontend.rule=Host(`becalm-api.arkano-ia.com`)"
