services:
  becalm-frontend:
    build: ./
    ports:
      - "8033:8033"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.becalm-frontend.rule=Host(`becalm-api.arkano-ia.com`)"
      - "traefik.http.services.becalm-frontend.loadbalancer.server.port=8033"
      - "traefik.http.routers.becalm-frontend.entrypoints=websecure"
      - "traefik.http.routers.becalm-frontend.tls.certresolver=letsencrypt"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
