services:
  becalm-frontend:
    build: ./
    ports:
      - "8033:8033"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.becalm-frontend.rule=Host(`becalm-api.arkano-ia.com`)"
      - "traefik.http.routers.becalm-frontend.entrypoints=web"
      - "traefik.http.services.becalm-frontend.loadbalancer.server.port=8033"
      # Si usas HTTPS, agrega estas líneas:
      - "traefik.http.routers.becalm-frontend.entrypoints=websecure"
      - "traefik.http.routers.becalm-frontend.tls.certresolver=letsencrypt"
